### ISSUE TITLE
Incorrect usage of _observerCallback

### ISSUE THREAD

**Issue by kostko** [peerlibrary/meteor-peerdb-migrations#1]
The `globals.Document._setupMigrations` method incorrectly uses `_observerCallback` from PeerDB. This results in errors similar to the following:

```
E20160226-16:06:59.653(1) (lib.coffee:1181) PeerDB exception: TypeError: Cannot call method 'apply' of undefined: [ {} ]
E20160226-16:06:59.654(1) (lib.coffee:1182) TypeError: Cannot call method 'apply' of undefined
    at packages/peerlibrary_peerdb/lib.coffee:1176:11
    at packages/mongo/observe_multiplex.js:183:1
    at Array.forEach (packages/es5-shim/.npm/package/node_modules/es5-shim/es5-shim.js:417:1)
    at Function._.each._.forEach (packages/underscore/underscore.js:105:1)
    at Object.task (packages/mongo/observe_multiplex.js:177:1)
    at [object Object]._.extend._run (packages/meteor/fiber_helpers.js:147:1)
    at packages/meteor/fiber_helpers.js:125:1
```

The cause is the following line in `server.coffee`:
- https://github.com/peerlibrary/meteor-peerdb-migrations/blob/master/server.coffee#L555

The first argument should be something else, not a function.

**Comment by mitar** [comment]
Fixed. Thanks for reporting.
